# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=200)),
                ('genre', models.CharField(choices=[('DET', 'Detective'), ('NOV', 'Novel'), ('NON_FICT', 'Non-fiction')], default='NOV', max_length=10)),
                ('date_pub', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_text', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.Status'),
        ),
    ]
