# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='date_pub',
            field=models.DateTimeField(auto_now=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('DET', 'Detective'), ('NOV', 'Novel'), ('NON_FICT', 'Non-fiction')], default='NOV', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.Language'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_text',
            field=models.CharField(max_length=100),
        ),
    ]
