# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-31 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0004_book_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_pub',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
