# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-02 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0006_settings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='date_pub',
            new_name='date_pub_modified',
        ),
        migrations.AddField(
            model_name='book',
            name='date_pub_created',
            field=models.DateTimeField(editable=False, null=True, verbose_name='date published'),
        ),
    ]
